#конфигурация для деплоя различных сервисов в контейнерное окружение
#с использованием Docker
gateway:
  service:
    image: 
      name: ondubovickaya/rsoi_gatewayservice
      version: "v1"
    port: 8080
    type: "gateway"
    isGateway: true
car:
  service:
    image: 
        name: ondubovickaya/rsoi_carsservice
        version: "v1"
    port: 8070
    type: "service"
    database:
        name: cars
rental:
  service:
    image: 
      name: ondubovickaya/rsoi_rentalservice
      version: "v1"
    port: 8060
    type: "service"
    database:
        name: rentals
payment:
  service:
    image: 
      name: ondubovickaya/rsoi_paymentservice
      version: "v1"
    port: 8050
    type: "service"
    database:
        name: payments
